services:
  - type: web
    name: bytesource
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn online_test.wsgi
    staticPublishPath: staticfiles
