# Generated by Django 5.1.7 on 2025-06-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="signup_confirmation",
            field=models.BooleanField(default=False),
        ),
    ]
